sequenceDiagram
    participant S as Sensor (Hardware)
    participant A as Arduino (Firmware)
    participant C as App C# (WPF/MVVM)
    participant L as SqlLogger (BD)
    participant B as Bomba (Relevador)

    loop Cada 500ms
        S->>A: Señal Analógica (Voltaje)
        A->>A: Conversión ADC (0-1023)
        A->>C: Trama Serial "VAL:450\n"
        C->>C: Validar Umbral (Lógica C#)
        alt Valor < Umbral
            C->>L: Guarda Evento (Encendido) en BD
            C->>A: Comando "PUMP_ON" ('1')
            A->>B: Cerrar Relevador (Activar)
        else Valor >= Umbral
            C->>A: Comando "PUMP_OFF" ('0')
            A->>B: Abrir Relevador (Desactivar)
        end
        C->>C: Actualizar UI (Binding MVVM)
    end
